### ISSUE TITLE
Move DependencyManager and ModularManager component

### ISSUE THREAD

**Issue by andru255** [frontend-labs/yosonjs#24]
It needs order or rename the components DependencyManager and ModularManager because are like a wrappers of real components used like a Dependency or Modular.

**Comment by jansanchez** [comment]
genial

2015-04-03 15:40 GMT-05:00 Andrés <notifications@github.com>:

> Closed #24 <https://github.com/frontend-labs/yosonjs/issues/24> via
> f88ae64
> <https://github.com/frontend-labs/yosonjs/commit/f88ae648bd6daddce8090c4289ade7399e36ecb1>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/frontend-labs/yosonjs/issues/24#event-272974782>.
>



-- 
 Kind regards, *Jan Sanchez Alarcon*
*Jefe de Desarrollo Móvil*
jan.sanchez@orbis.pe
(511) 3116500 anexo 2640 | 977743538 | 930651390
Jr. José Galvez #692, Miraflores

  UNT - Software Factory
