### ISSUE TITLE
yOSON create conflict with others libraries

### ISSUE THREAD

**Issue by carloshs92** [frontend-labs/yosonjs#32]

**Comment by jansanchez** [comment]
Hola @carloshs92  exactamente cual es el escenario? favor tu apoyo para comentarnos mas acerca del bug.

**Comment by carloshs92** [comment]
yOSON, para evitar conflictos de module con node, lo que actualmente se hace era converitr el module en un objeto sin embargo muchas librerias utilizan el siguiente tipo de validación
<pre><code>if ( typeof module != 'undefined' && module.exports ) {
	module.exports = IScroll;
} else {
	window.IScroll = IScroll;
}</code></pre>
Este tipo de validación consulta por el module y como ahora siempre existe estas librerias creen que están en node y no en web y por ende dan conflictos.

**Comment by jansanchez** [comment]
@carloshs92  sería genial si la condicional puede ser true y no se evalúa desde un false, aprovechando de que el objeto **window** no se declara en un ámbito de Node, esta condicional funcionaría para las 2 y no traería conflictos:

```javascript
if (typeof window === 'undefined') {
    module.exports = yOSON;
}
```

En lugar de:

```javascript
if (typeof module !== 'undefined' && module.exports) {
    module.exports = yOSON;
}
```
