### ISSUE TITLE
Error: The module 'name_module' can't be loaded

### ISSUE THREAD

**Issue by renaco** [frontend-labs/yosonjs#36]
When deploy on server with protocol on https url's, dependencies is rejected for browser and appears these message in console:

> Mixed Content: The page at 'https://wallet.pre.2b.pagoefectivo.pe/Afiliacion/paso1' was loaded over > HTTPS, but requested an insecure script  'http://wallet.pre.2b.pagoefectivo.pe/Content/static/pesaldo/js/dist/libs/jquery.inputmask/dist/jquery.inputmask.bundle.min.js?version'. This request has been blocked; the content must be served over > HTTPS.Dependency.request @ yoson.js:141
 yoson.js:12 Error: the module date_mask can't be loaded

Can load with secure protocol for next deployment?

Regards!

**Comment by andru255** [comment]
thanks @renaco for the new feature, closed with commit https://github.com/frontend-labs/yosonjs/commit/0bf7c15a88104018cd151013397aae0a9a2d8820
